In [ ]:
#NUMPY ASSIGNMENT

In [ ]:
                                                     #THEORETICAL QUESTIONS

In [ ]:
#Q1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does enhance Python's capabilities for numerical operations?
'''
NumPy, short for Numerical Python, is a crucial library for scientific computing and data analysis in Python. Here's why
Purpose:

NumPy provides support for:
Multi-dimensional arrays and matrices: It offers efficient storage and manipulation of large datasets.
Mathematical functions: It includes a comprehensive set of mathematical functions to operate on these arrays.

Advantages:

1.Performance: Written in C, NumPy is much faster than Python’s native lists for numerical computations, thanks to optimized operations and efficient memory usage.
2.Convenience: With its powerful N-dimensional array object (ndarray), handling numerical data becomes both easy and intuitive.
3.Functionality: Supports a variety of mathematical, statistical, and linear algebra operations.
4.Interoperability: Works seamlessly with other libraries like SciPy, Pandas, and Matplotlib, enhancing its utility.
5.Vectorization: Allows vectorized operations, eliminating the need for explicit loops and making code more concise and readable.

Enhancing Python’s Capabilities:

1.Efficient Data Storage: NumPy arrays are more memory-efficient compared to Python lists.
2.Speed: Operations on NumPy arrays are performed at C speed, significantly boosting performance.
3.Set of Functions: Offers comprehensive mathematical functions and tools for complex calculations.
4.Array Broadcasting: Supports broadcasting, simplifying arithmetic operations on arrays of different shapes.
'''

In [2]:
#Q2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?
'''
Comparison:
Purpose: Both functions are used to compute the average of the input data.
Basic Functionality: Without weights, both np.mean() and np.average() produce the same result by calculating the arithmetic mean of the array elements.
Axis Support: Both functions support the axis parameter, allowing you to calculate the mean along a specific axis of an array.

Contrast:

Weighting:
np.mean(): Does not support weighting. It calculates a simple arithmetic mean.
np.average(): Supports weighting. It can calculate a weighted average if weights are provided through the weights parameter.

Syntax:
np.mean(): np.mean(array, axis=None)
np.average(): np.average(array, axis=None, weights=None)

Usage Scenarios:
Use np.mean(): When you need a straightforward calculation of the mean without any weighting considerations.
Use np.average(): When you need to compute a weighted average, taking into account different weights for different elements of the array.

When to Use Each:

Use np.mean(): When you want a straightforward calculation of the mean without any weighting. For example:
'''
import numpy as np
data = np.array([1, 2, 3, 4, 5])
mean = np.mean(data)
print(mean)  

#Use np.average(): When you need to calculate the average of an array with weights. For example:
import numpy as np
data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
average = np.average(data, weights=weights)
print(average)  

3.0
3.6666666666666665


In [4]:
#Q3.Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.
'''
In NumPy, you can reverse arrays along different axes using slicing techniques and specific functions like np.flip
'''
# Reversing a 1D Array: We can reverse a 1D array using slicing.
import numpy as np

# Creating a 1D array
array_1d = np.array([1, 2, 3, 4, 5])

# Reversing the array
reversed_array_1d = array_1d[::-1]

print(reversed_array_1d)  

#Reversing a 2D Array: We can reverse a 2D array along different axes using np.flip and slicing.

# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Reversing along axis 0
reversed_array_2d_axis0 = np.flip(array_2d, axis=0)

print(reversed_array_2d_axis0)

#Reverse along axis 1 (columns):

# Reversing along axis 1
reversed_array_2d_axis1 = np.flip(array_2d, axis=1)

print(reversed_array_2d_axis1)

# Reverse the whole 2D array: We can reverse the entire 2D array by flipping it along both axes.
# Reversing the entire array
reversed_array_2d = np.flip(array_2d)

print(reversed_array_2d)


[5 4 3 2 1]
[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [ ]:
#Q4.How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

'''
We can determine the data type of elements in a NumPy array using the dtype attribute. This shows what kind of data the array holds, 
which is crucial for memory management and performance optimization.

Importance of Data Types:

Memory Management:
NumPy arrays are more memory-efficient than Python lists because they are densely packed in memory.
The data type (dtype) defines the size of each element, allowing NumPy to allocate a fixed and compact block of memory.
For instance, using int8 (8-bit integer) instead of int64 (64-bit integer) can significantly reduce memory usage.

Performance:
Fixed data types allow NumPy to perform operations more quickly since it doesn't need to check the type of each element at runtime.
Operations on NumPy arrays are performed at C speed, which is much faster than equivalent operations on Python lists.
Optimized numerical operations: NumPy uses vectorized operations, which are faster and more efficient than looping through elements in Python.
'''

In [ ]:
#Q5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
'''
Definition:
ndarray stands for "N-dimensional array". It's a central feature of the NumPy library and provides a way to efficiently store and manipulate large datasets in multiple dimensions.

Key Features:
1.Homogeneous Data: All elements in an ndarray must be of the same data type, allowing for efficient storage and operations.

2.N-dimensional: Supports arrays of any dimension, making it versatile for various data structures (1D, 2D, 3D, etc.).

3.Efficient Memory Usage: Uses contiguous blocks of memory, which enhances performance and memory efficiency.

4.Advanced Indexing and Slicing: Supports sophisticated indexing techniques, including boolean masking, integer indexing, and slicing.

5.Vectorized Operations: Allows for element-wise operations without explicit loops, leveraging optimized C and Fortran code.

6.Broadcasting: Enables operations on arrays of different shapes, automatically expanding the smaller array to match the larger one.

7.Built-in Functions: Comes with a plethora of mathematical, statistical, and algebraic functions.

Differences from Standard Python Lists:

1.Performance:

ndarray: Highly optimized for numerical operations, leveraging low-level implementations.
Python Lists: Slower for numerical operations as they lack such optimizations.

2.Memory Efficiency:

ndarray: More memory-efficient due to homogeneous data types and contiguous memory allocation.
Python Lists: Less efficient as they store references to objects, requiring more memory.

3.Element-wise Operations:

ndarray: Supports vectorized operations, enabling element-wise arithmetic without loops.
Python Lists: Requires explicit loops for element-wise operations.

4.Functionality:

ndarray: Packed with built-in functions for complex mathematical operations.
Python Lists: Lack built-in support for advanced mathematical operations.
'''


In [8]:
#Q6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.
'''
Memory Efficiency:
Contiguous Memory Blocks: NumPy arrays are stored in contiguous blocks of memory, ensuring efficient storage and quick access.
Python lists, however, store references to objects, which is less memory-efficient.

Homogeneous Data Types: NumPy arrays contain elements of a single data type. 
This consistency allows for optimized storage and faster computations. Python lists, being heterogeneous, can store mixed data types,
increasing memory usage and reducing performance.

Performance:
Vectorized Operations: NumPy supports element-wise operations without explicit loops, 
thanks to vectorization. These operations are optimized at a low level, significantly boosting speed.
Typically, we’ll find that the NumPy operation is much faster due to optimized C and Fortran code running under the hood.
'''

import numpy as np
import time

# Creating large arrays
array = np.arange(1e6)
list_ = list(range(int(1e6)))

# Timing NumPy operation
start_time = time.time()
array_squared = array ** 2
print("NumPy operation took:", time.time() - start_time)

# Timing list operation
start_time = time.time()
list_squared = [x ** 2 for x in list_]
print("List operation took:", time.time() - start_time)
'''
Broadcasting:
Automatic Expansion: NumPy's broadcasting allows it to perform operations on arrays of different shapes seamlessly, expanding them as needed. 
This feature saves memory and coding effort.
'''
a = np.array([1, 2, 3])
b = np.array([[4], [5], [6]])
result = a + b 

'''
Built-in Mathematical Functions:
Comprehensive Library: NumPy offers a wide range of mathematical, statistical, and linear algebra functions that are highly optimized and 
faster than equivalent Python list operations.
'''
# Mean calculation
np_mean = np.mean(array)
py_mean = sum(list_) / len(list_)

'''
Case Study - Matrix Multiplication:
Matrix operations, such as multiplication, are dramatically faster with NumPy:
'''

NumPy operation took: 0.008929252624511719
List operation took: 0.09714794158935547


'\nCase Study - Matrix Multiplication:\nMatrix operations, such as multiplication, are dramatically faster with NumPy:\n'

In [10]:
#Q7.Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.
'''
vstack():
Purpose: Vertically stacks arrays. Think of it as stacking arrays on top of each other.
Usage: Used when you want to concatenate arrays along the vertical axis (axis 0).

hstack():
Purpose: Horizontally stacks arrays. Think of it as placing arrays side by side.
Usage: Used when you want to concatenate arrays along the horizontal axis (axis 1).
'''
#exaple vstack()
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Using vstack
vstacked_array = np.vstack((array1, array2))

print(vstacked_array)

#example hstack()
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Using hstack
hstacked_array = np.hstack((array1, array2))

print(hstacked_array)


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [12]:
#Q8.Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions?
'''
fliplr()
Purpose: Flips the array left to right (horizontally).
Effect on Dimensions: The leftmost column becomes the rightmost column and vice versa.
Usage: Mainly used for 2D arrays or higher-dimensional arrays where you want to flip elements along the horizontal axis.

flipud()
Purpose: Flips the array up to down (vertically).
Effect on Dimensions: The top row becomes the bottom row and vice versa.
Usage: Used for 2D arrays or higher-dimensional arrays where you want to flip elements along the vertical axis.
'''
#fliplr() example
import numpy as np

array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

flipped_lr = np.fliplr(array_2d)
print(flipped_lr)

#flipud() example
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

flipped_ud = np.flipud(array_2d)
print(flipped_ud)


[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [14]:
#Q9.Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
'''
array_split() in NumPy is used to split an array into multiple sub-arrays. It’s quite handy when you need to divide an array into smaller
, more manageable chunks.

Functionality:
Basic Usage: array_split(array, indices_or_sections)

array: The input array to be split.
indices_or_sections: If an integer, it splits the array into that many equal or nearly equal parts. If a list, it uses the entries as split indices.

Handling Uneven Splits:
When the array doesn't divide evenly:
Integer Argument: NumPy distributes the sub-arrays as evenly as possible. Some of the sub-arrays might have more elements than others.
'''
import numpy as np

array = np.arange(10)
split_arrays = np.array_split(array, 3)
for arr in split_arrays:
    print(arr)

#List Argument: If a list of indices is provided, it splits the array at those indices.
split_arrays = np.array_split(array, [3, 5, 7])
for arr in split_arrays:
    print(arr)
'''
Flexibility: Handles both even and uneven splits efficiently.
Customization: Allows for precise control over the split points with list arguments.
array_split() is a versatile tool for breaking down large arrays into smaller parts, ensuring that even uneven splits are managed gracefully.
'''

[0 1 2 3]
[4 5 6]
[7 8 9]
[0 1 2]
[3 4]
[5 6]
[7 8 9]


In [16]:
#Q10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?
'''
Vectorization:
Vectorization is the process of performing operations on entire arrays rather than using explicit loops. By leveraging NumPy's capabilities, 
vectorized operations are implemented in optimized C code, making them significantly faster than standard Python loops
Vectorization allows us to operate on the entire array at once, significantly improving performance.
'''
import numpy as np

# Using loops
array = np.array([1, 2, 3, 4, 5])
result = np.zeros_like(array)
for i in range(len(array)):
    result[i] = array[i] ** 2

# Using vectorization
result_vectorized = array ** 2

print(result)           
print(result_vectorized)  

'''
Broadcasting:
Broadcasting is a method that allows NumPy to perform operations on arrays of different shapes. It "stretches" the smaller array to match
the shape of the larger array without making actual copies of the data, leading to efficient memory usage and performance gains.

Rules of Broadcasting:
If the arrays differ in their number of dimensions, the shape of the smaller-dimensional array is padded with ones on its left side.
If the shape of the arrays doesn’t match, NumPy tries to stretch the smaller array along the mismatched dimension.
'''
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([[1], [2], [3]])

# Broadcasting addition
result = array1 + array2

print(result)


[ 1  4  9 16 25]
[ 1  4  9 16 25]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [ ]:
                                                    #PRACTICAL QUESTIONS

In [18]:
#Q1.Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns?
import numpy as np

# Creating a 3x3 array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))

print("Original Array:")
print(array)

# Interchanging rows and columns (transpose)
transposed_array = array.T

print("\nTransposed Array:")
print(transposed_array)


Original Array:
[[41 42 14]
 [89 40 59]
 [43 19 24]]

Transposed Array:
[[41 89 43]
 [42 40 19]
 [14 59 24]]


In [20]:
#Q2.Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array?

#generating 1D array
import numpy as np

# Create a 1D array with 10 elements
array_1d = np.arange(10)

print("Original 1D Array:")
print(array_1d)

#reshape it into 2X5 array

# Reshape into a 2x5 array
array_2x5 = array_1d.reshape((2, 5))

print("\n2x5 Array:")
print(array_2x5)

# Reshape into 5X2 array

array_5x2 = array_1d.reshape((5, 2))

print("\n5x2 Array:")
print(array_5x2)


Original 1D Array:
[0 1 2 3 4 5 6 7 8 9]

2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [22]:
#Q3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

import numpy as np

# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)

print("Original 4x4 Array:")
print(array_4x4)

# Add a border of zeros around the 4x4 array to form a 6x6 array
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print("\n6x6 Array with Border of Zeros:")
print(array_6x6)


Original 4x4 Array:
[[0.46618508 0.7308907  0.05641032 0.89815672]
 [0.89098499 0.59436379 0.8554135  0.77589643]
 [0.00096823 0.72546922 0.46209907 0.7608573 ]
 [0.20454137 0.44889794 0.73732855 0.46077131]]

6x6 Array with Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.46618508 0.7308907  0.05641032 0.89815672 0.        ]
 [0.         0.89098499 0.59436379 0.8554135  0.77589643 0.        ]
 [0.         0.00096823 0.72546922 0.46209907 0.7608573  0.        ]
 [0.         0.20454137 0.44889794 0.73732855 0.46077131 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [24]:
#Q4. Using NumPy, create an array of integers from 10 to 60 with a step of 5?

import numpy as np

# Creating the array
array = np.arange(10, 65, 5)

print(array)


[10 15 20 25 30 35 40 45 50 55 60]


In [26]:
#Q5.Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

import numpy as np

# Create the array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_arr = np.char.upper(arr)
lowercase_arr = np.char.lower(arr)
titlecase_arr = np.char.title(arr)

print("Original Array:", arr)
print("Uppercase Array:", uppercase_arr)
print("Lowercase Array:", lowercase_arr)
print("Titlecase Array:", titlecase_arr)


Original Array: ['python' 'numpy' 'pandas']
Uppercase Array: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase Array: ['python' 'numpy' 'pandas']
Titlecase Array: ['Python' 'Numpy' 'Pandas']


In [28]:
#Q6.Generate a NumPy array of words. Insert a space between each character of every word in the array.

import numpy as np

# Create an array of words
words = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_words = np.char.join(' ', words)

print("Original Array:", words)
print("Spaced Words Array:", spaced_words)


Original Array: ['python' 'numpy' 'pandas']
Spaced Words Array: ['p y t h o n' 'n u m p y' 'p a n d a s']


In [30]:
#Q7.Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division?

import numpy as np

# Create two 2D arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)

# Element-wise addition
addition = np.add(array1, array2)
print("\nElement-wise Addition:")
print(addition)

# Element-wise subtraction
subtraction = np.subtract(array1, array2)
print("\nElement-wise Subtraction:")
print(subtraction)

# Element-wise multiplication
multiplication = np.multiply(array1, array2)
print("\nElement-wise Multiplication:")
print(multiplication)

# Element-wise division
division = np.divide(array1, array2)
print("\nElement-wise Division:")
print(division)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise Division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [32]:
#Q8.Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

import numpy as np

# Creating a 5x5 identity matrix
identity_matrix = np.eye(5)

print("5x5 Identity Matrix:")
print(identity_matrix)

# Extracting the diagonal elements
diagonal_elements = np.diag(identity_matrix)

print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


In [34]:
#Q9.Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

import numpy as np

# Generate an array of 100 random integers between 0 and 1000
array = np.random.randint(0, 1000, size=100)

print("Array of 100 random integers:")
print(array)

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

# Find prime numbers in the array
prime_numbers = np.array([num for num in array if is_prime(num)])

print("\nPrime numbers in the array:")
print(prime_numbers)


Array of 100 random integers:
[ 20 720 474 705 668  98 959 343 241 411 675 187 576 899 844 857 345 730
 157 589 354 369 403 680 712 201  27 343 272 440 937 354 768 508  73 759
  28 941 289 209 238 496 871  36 333  88 618  44 371 865 461 847 164 423
 615 423 450 173 136 867 128 540 120 348 789 212  63  21 999 624 772 758
 533 286 961 322 640 486 800 569 305   2 951 542 364 177 409 697 483 828
  57 332 726 230 859 877 699 712 950  44]

Prime numbers in the array:
[241 857 157 937  73 941 461 173 569   2 409 859 877]


In [48]:
#Q10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

import numpy as np

# Generate random sales data for 30 days
daily_sales = np.random.randint(100, 1000, size=30)
print("Daily Sales for a Month:")
print(daily_sales)

# Ensure we can reshape the array for weekly calculations
try:
    # Reshape the array to (4 weeks, 7 days)
    weekly_sales = daily_sales.reshape((4, 7))
    print("\nWeekly Sales:")
    print(weekly_sales)

    # Calculate the average sales for each week
    weekly_averages = np.mean(weekly_sales, axis=1)
    print("\nWeekly Averages:")
    print(weekly_averages)
except ValueError as e:
    print("Error:", e)
    print("Ensure the total number of days can be reshaped into complete weeks.")

# Alternative approach if reshaping is the issue
if daily_sales.size != 28:  # 4 weeks * 7 days
    print("\nAdjusting array to fit weeks...")
    daily_sales = daily_sales[:28]  # Use only the first 28 days for weekly calculation
    weekly_sales = daily_sales.reshape((4, 7))
    print("\nAdjusted Weekly Sales:")
    print(weekly_sales)

    weekly_averages = np.mean(weekly_sales, axis=1)
    print("\nAdjusted Weekly Averages:")
    print(weekly_averages)


Daily Sales for a Month:
[447 250 481 103 479 519 792 153 149 994 896 679 593 498 133 141 432 803
 311 641 324 321 431 785 340 239 102 347 806 118]
Daily Sales for a Month:
[465 988 252 276 813 550 383 966 797 782 619 475 295 183 832 431 795 608
 376 641 486 330 686 869 817 964 374 979 420 244]
Error: cannot reshape array of size 30 into shape (4,7)
Ensure the total number of days can be reshaped into complete weeks.

Adjusting array to fit weeks...

Adjusted Weekly Sales:
[[465 988 252 276 813 550 383]
 [966 797 782 619 475 295 183]
 [832 431 795 608 376 641 486]
 [330 686 869 817 964 374 979]]

Adjusted Weekly Averages:
[532.42857143 588.14285714 595.57142857 717.        ]
